<Project Sdk="Aspire.AppHost.Sdk/13.5.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>bd826f8d-069e-4639-a56b-1b9679c1fca0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <PackageReference Include="Aspire.Hosting.NodeJs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Auth019\Auth019.csproj" />
    <ProjectReference Include="..\ExpenseTracker019.Api\ExpenseTracker019.Api.csproj" />
  </ItemGroup>

</Project>
